import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffectOnce } from '@/lib/hooks'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  useEffectOnce(() => {
      import("../threejs/scene")

    return () => window.location.reload()
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div id="threejsCanvas"></div>
      </main>
    </>
  )
}
